name: Planfi Api

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: false

env:
  CONNECTION_STRING: "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=postgres;"
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - uses: actions/checkout@v2

      - name: Use gcloud CLI
        run: gcloud info


      - uses: microsoft/variable-substitution@v1 
        with:
          files: "Planfi.Api/appsettings.json"
        env:
          ConnectionStrings.WebApiDatabase: ${{ env.CONNECTION_STRING }}

      - name: Read PlanfiApi -> appsettings.json
        run: "cat Planfi.Api/appsettings.json"

      - name: Build and tag image 
        run: docker build -f Planfi.Api/Dockerfile -t eu.gcr.io/${{secrets.GCP_PROJECT_ID}}/planfi-api .

      - name: Configure Docker to use Google Cloud Platform
        run: gcloud auth configure-docker --quiet

      - name: Docker push image
        run: docker push eu.gcr.io/${{secrets.GCP_PROJECT}}/planfi-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Cloud run deploy
        run: gcloud run deploy planfi-api --image eu.gcr.io/${{env.GCP_PROJECT}}/planfi-api --region=europe-west1 --project=${{env.GCP_PROJECT}} --memory=1024M --max-instances=10 --cpu=2 --timeout=120 --port=5005
  
      - name: Cloud run serve traffic
        run: gcloud run services update-traffic planfi-api --to-latest --platform=managed --region=europe-west1