name: Planfi Api

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

env:
  DIGITALOCEAN_ACCESS_TOKEN: "faa1634b6ea17366f3c38435c9f3a2cc95fc721db60aa6034c6d992e19b2f2bc"
  CONNECTION_STRING: "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=postgres;"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Build image 
        run: docker build Planfi.Api/Dockerfile -t .

      - name: Read MyShare.Core.Api -> appsettings.json
        run: "cat MyShare.Core.Api/appsettings.json"

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

      - name: Tag image 
        run:
          docker tag sample/my-page 
          registry.digitalocean.com/my-sample-registry/my-sample-page:${{github.event.inputs.version }}

  push:
    runs-on: ubuntu-latest
    needs: build

      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/my-sample-registry/my-sample-page:${{ github.event.inputs.version }}
