name: Planfi Api

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: false

env:
  DIGITALOCEAN_ACCESS_TOKEN: "faa1634b6ea17366f3c38435c9f3a2cc95fc721db60aa6034c6d992e19b2f2bc"
  CONNECTION_STRING: "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=postgres;"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Build and tag image 
        run: docker build -f Planfi.Api/Dockerfile -t registry.digitalocean.com/planfi/planfi-api-production .

      - name: Read PlanfiApi -> appsettings.json
        run: "cat Planfi.Api/appsettings.json"

      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ env.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600

# deicde where to push exactly
  # push:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:

      - name: Show all docker images available
        run: 
          docker images

      - name: Push image to DO Container Registry 
        run: 
          docker push registry.digitalocean.com/planfi/planfi-api-production:latest
