name: Planfi Api

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: false

env:
  # SSL encryption is recommended when using Public IP to connect to the instance.
  CONNECTION_STRING: "Host=34.135.254.64;Port=5432;Username=postgres;Password=postgres;Database=postgres;"
  RUN_REGION: us-central1
  SERVICE_NAME: planfi-api
  Origins: "https://plan-fi.pl,http://plan-fi.pl"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      - uses: actions/checkout@v2

      - name: Use gcloud CLI
        run: gcloud info

      - uses: microsoft/variable-substitution@v1 
        with:
          files: "Planfi.Api/appsettings.json"
        env:
          ConnectionStrings.WebApiDatabase: ${{ env.CONNECTION_STRING }}
          Origins: ${{ env.Origins }}

      - name: Read PlanfiApi -> appsettings.json
        run: "cat Planfi.Api/appsettings.json"

      - name: Build and tag image 
        run: docker build --platform linux/amd64 -f Planfi.Api/Dockerfile -t eu.gcr.io/${{secrets.GCP_PROJECT_ID}}/planfi-api .

      - name: Configure Docker to use Google Cloud Platform
        run: gcloud auth configure-docker --quiet

      - name: Docker push image
        run: docker push eu.gcr.io/${{secrets.GCP_PROJECT_ID}}/planfi-api

      - name: Cloud run deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "eu.gcr.io/${{secrets.GCP_PROJECT_ID}}/planfi-api" \
            --platform "managed" \
            --port 9001

      - name: Cloud run serve traffic
        run: gcloud run services update-traffic planfi-api --to-latest --platform=managed --region=${{env.RUN_REGION}}
