name: Planfi Front

on:
  workflow_dispatch:

env:
  CloudStorageBucket: "planfi-bucket"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: actions/checkout@v2

      - name: Build and deploy frontend to static GCP Cloud Storage
        run: |
          cd ./Planfi.Front/
          npm install
          CI=false npm run-script build
          gsutil -h "Cache-Control:public, max-age=60, no-transform" rsync -d -r ./build gs://${{env.CloudStorageBucket}}/
