name: Planfi Front

on:
  workflow_dispatch:

env:
  CloudStorageBucket: "planfi-bucket"
  GCP_PROJECT: "prefab-rampart-231613"
  GCP_SA_KEY: "bb576e5141cf904e0c59e8bec3d4385f1e5ab907"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/checkout@v2

      - name: Install Npm
        run: |
          cd ./Planfi.Front/
          npm i
      - name: Run Npm
        run: |
          cd ./Planfi.Front/
          npm start
      - name: Deploy
        run: |
          gsutil -h "Cache-Control:public, max-age=60, no-transform" rsync -d -r ./build gs://${{env.CloudStorageBucket}}/
      # gcloud compute url-maps invalidate-cdn-cache myshare-prod-lb --path '/app.myshare.today/*'
