name: Planfi Api

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: false

env:
  CONNECTION_STRING: "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=postgres;"
  GCP_PROJECT: "focus-pottery-330316"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo 
        uses: actions/checkout@v2

      - name: Build and tag image 
        run: docker build -f Planfi.Api/Dockerfile -t eu.gcr.io/${{env.GCP_PROJECT}}/planfi-api .

      - name: Read PlanfiApi -> appsettings.json
        run: "cat Planfi.Api/appsettings.json"

      - name: Configure Docker to use Google Cloud Platform
        run: gcloud auth configure-docker --quiet

      - name: Docker push image
        run: docker push eu.gcr.io/${{env.GCP_PROJECT}}/planfi-api

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Cloud run deploy
        run: gcloud run deploy planfi-api --image eu.gcr.io/${{dev.GCP_PROJECT}}/planfi-api --region=europe-west1 --project=${{dev.GCP_PROJECT}} --memory=1024M --max-instances=10 --cpu=2 --timeout=120 --port=5005
  
      - name: Cloud run serve traffic
        run: gcloud run services update-traffic planfi-api --to-latest --platform=managed --region=europe-west1